#!/bin/bash

if [[ $# -ne 2 ]]; then
    echo "usage $0 architecture (e.g. arm, powerpc) bsp (eg. beatnik, beagleboneblack)" >&2
    exit 2
fi

#RTEMS development
export RTEMS_VERSION=7
export RTEMS_RELEASE=7
export RTEMS_CPU=$1
export RTEMS_BSP=$2
export RTEMS_ARCH=${RTEMS_CPU}-rtems${RTEMS_VERSION}
SCRIPT=$(readlink -f $0)
export RTEMS_ROOT=`dirname $SCRIPT`/rtems/${RTEMS_RELEASE}

# Add freebsd network
git clone https://gitlab.rtems.org/rtems/pkg/rtems-libbsd.git
cd rtems-libbsd/
git checkout 7-freebsd-14
git submodule init
git submodule update rtems_waf

./waf configure --prefix=${RTEMS_ROOT} --rtems-bsps=${RTEMS_CPU}/${RTEMS_BSP} --buildset=buildset/default.ini
./waf
./waf install
